package Proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ETO.proto

public final class ETO {
    private ETO() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface TaskResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TaskResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string status = 1;</code>
         *
         * <pre>
         *OK, FAILED -&gt;comment
         * </pre>
         */
        java.lang.String getStatus();
        /**
         * <code>optional string status = 1;</code>
         *
         * <pre>
         *OK, FAILED -&gt;comment
         * </pre>
         */
        com.google.protobuf.ByteString
        getStatusBytes();

        /**
         * <code>optional string comment = 2;</code>
         */
        java.lang.String getComment();
        /**
         * <code>optional string comment = 2;</code>
         */
        com.google.protobuf.ByteString
        getCommentBytes();

        /**
         * <code>optional double value = 3;</code>
         */
        double getValue();

        /**
         * <code>optional int32 executionTime = 4;</code>
         */
        int getExecutionTime();
    }
    /**
     * Protobuf type {@code TaskResult}
     */
    public  static final class TaskResult extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:TaskResult)
            TaskResultOrBuilder {
        // Use TaskResult.newBuilder() to construct.
        private TaskResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }
        private TaskResult() {
            status_ = "";
            comment_ = "";
            value_ = 0D;
            executionTime_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private TaskResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            status_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            comment_ = s;
                            break;
                        }
                        case 25: {

                            value_ = input.readDouble();
                            break;
                        }
                        case 32: {

                            executionTime_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ETO.internal_static_TaskResult_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ETO.internal_static_TaskResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ETO.TaskResult.class, ETO.TaskResult.Builder.class);
        }

        public static final int STATUS_FIELD_NUMBER = 1;
        private volatile java.lang.Object status_;
        /**
         * <code>optional string status = 1;</code>
         *
         * <pre>
         *OK, FAILED -&gt;comment
         * </pre>
         */
        public java.lang.String getStatus() {
            java.lang.Object ref = status_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                status_ = s;
                return s;
            }
        }
        /**
         * <code>optional string status = 1;</code>
         *
         * <pre>
         *OK, FAILED -&gt;comment
         * </pre>
         */
        public com.google.protobuf.ByteString
        getStatusBytes() {
            java.lang.Object ref = status_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                status_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COMMENT_FIELD_NUMBER = 2;
        private volatile java.lang.Object comment_;
        /**
         * <code>optional string comment = 2;</code>
         */
        public java.lang.String getComment() {
            java.lang.Object ref = comment_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                comment_ = s;
                return s;
            }
        }
        /**
         * <code>optional string comment = 2;</code>
         */
        public com.google.protobuf.ByteString
        getCommentBytes() {
            java.lang.Object ref = comment_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                comment_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VALUE_FIELD_NUMBER = 3;
        private double value_;
        /**
         * <code>optional double value = 3;</code>
         */
        public double getValue() {
            return value_;
        }

        public static final int EXECUTIONTIME_FIELD_NUMBER = 4;
        private int executionTime_;
        /**
         * <code>optional int32 executionTime = 4;</code>
         */
        public int getExecutionTime() {
            return executionTime_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getStatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, status_);
            }
            if (!getCommentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, comment_);
            }
            if (value_ != 0D) {
                output.writeDouble(3, value_);
            }
            if (executionTime_ != 0) {
                output.writeInt32(4, executionTime_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getStatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, status_);
            }
            if (!getCommentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, comment_);
            }
            if (value_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, value_);
            }
            if (executionTime_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, executionTime_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        public static ETO.TaskResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ETO.TaskResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ETO.TaskResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ETO.TaskResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ETO.TaskResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static ETO.TaskResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static ETO.TaskResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static ETO.TaskResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static ETO.TaskResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static ETO.TaskResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(ETO.TaskResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code TaskResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TaskResult)
                ETO.TaskResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ETO.internal_static_TaskResult_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ETO.internal_static_TaskResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ETO.TaskResult.class, ETO.TaskResult.Builder.class);
            }

            // Construct using ETO.TaskResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                status_ = "";

                comment_ = "";

                value_ = 0D;

                executionTime_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ETO.internal_static_TaskResult_descriptor;
            }

            public ETO.TaskResult getDefaultInstanceForType() {
                return ETO.TaskResult.getDefaultInstance();
            }

            public ETO.TaskResult build() {
                ETO.TaskResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ETO.TaskResult buildPartial() {
                ETO.TaskResult result = new ETO.TaskResult(this);
                result.status_ = status_;
                result.comment_ = comment_;
                result.value_ = value_;
                result.executionTime_ = executionTime_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ETO.TaskResult) {
                    return mergeFrom((ETO.TaskResult)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ETO.TaskResult other) {
                if (other == ETO.TaskResult.getDefaultInstance()) return this;
                if (!other.getStatus().isEmpty()) {
                    status_ = other.status_;
                    onChanged();
                }
                if (!other.getComment().isEmpty()) {
                    comment_ = other.comment_;
                    onChanged();
                }
                if (other.getValue() != 0D) {
                    setValue(other.getValue());
                }
                if (other.getExecutionTime() != 0) {
                    setExecutionTime(other.getExecutionTime());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ETO.TaskResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ETO.TaskResult) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object status_ = "";
            /**
             * <code>optional string status = 1;</code>
             *
             * <pre>
             *OK, FAILED -&gt;comment
             * </pre>
             */
            public java.lang.String getStatus() {
                java.lang.Object ref = status_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    status_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string status = 1;</code>
             *
             * <pre>
             *OK, FAILED -&gt;comment
             * </pre>
             */
            public com.google.protobuf.ByteString
            getStatusBytes() {
                java.lang.Object ref = status_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    status_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string status = 1;</code>
             *
             * <pre>
             *OK, FAILED -&gt;comment
             * </pre>
             */
            public Builder setStatus(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string status = 1;</code>
             *
             * <pre>
             *OK, FAILED -&gt;comment
             * </pre>
             */
            public Builder clearStatus() {

                status_ = getDefaultInstance().getStatus();
                onChanged();
                return this;
            }
            /**
             * <code>optional string status = 1;</code>
             *
             * <pre>
             *OK, FAILED -&gt;comment
             * </pre>
             */
            public Builder setStatusBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                status_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object comment_ = "";
            /**
             * <code>optional string comment = 2;</code>
             */
            public java.lang.String getComment() {
                java.lang.Object ref = comment_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    comment_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string comment = 2;</code>
             */
            public com.google.protobuf.ByteString
            getCommentBytes() {
                java.lang.Object ref = comment_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    comment_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string comment = 2;</code>
             */
            public Builder setComment(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                comment_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string comment = 2;</code>
             */
            public Builder clearComment() {

                comment_ = getDefaultInstance().getComment();
                onChanged();
                return this;
            }
            /**
             * <code>optional string comment = 2;</code>
             */
            public Builder setCommentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                comment_ = value;
                onChanged();
                return this;
            }

            private double value_ ;
            /**
             * <code>optional double value = 3;</code>
             */
            public double getValue() {
                return value_;
            }
            /**
             * <code>optional double value = 3;</code>
             */
            public Builder setValue(double value) {

                value_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional double value = 3;</code>
             */
            public Builder clearValue() {

                value_ = 0D;
                onChanged();
                return this;
            }

            private int executionTime_ ;
            /**
             * <code>optional int32 executionTime = 4;</code>
             */
            public int getExecutionTime() {
                return executionTime_;
            }
            /**
             * <code>optional int32 executionTime = 4;</code>
             */
            public Builder setExecutionTime(int value) {

                executionTime_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 executionTime = 4;</code>
             */
            public Builder clearExecutionTime() {

                executionTime_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:TaskResult)
        }

        // @@protoc_insertion_point(class_scope:TaskResult)
        private static final ETO.TaskResult DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new ETO.TaskResult();
        }

        public static ETO.TaskResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TaskResult>
                PARSER = new com.google.protobuf.AbstractParser<TaskResult>() {
            public TaskResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new TaskResult(input, extensionRegistry);
                } catch (RuntimeException e) {
                    if (e.getCause() instanceof
                            com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException)
                                e.getCause();
                    }
                    throw e;
                }
            }
        };

        public static com.google.protobuf.Parser<TaskResult> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TaskResult> getParserForType() {
            return PARSER;
        }

        public ETO.TaskResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_TaskResult_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_TaskResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\tETO.proto\"S\n\nTaskResult\022\016\n\006status\030\001 \001(" +
                        "\t\022\017\n\007comment\030\002 \001(\t\022\r\n\005value\030\003 \001(\001\022\025\n\rexe" +
                        "cutionTime\030\004 \001(\005b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_TaskResult_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TaskResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_TaskResult_descriptor,
                new java.lang.String[] { "Status", "Comment", "Value", "ExecutionTime", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
